### ISSUE TITLE
Request gets stuck with zio-http if the websocket upgrade fails

### ISSUE THREAD

**Issue by vigoo** [ghostdogpr/caliban#1469] opened 2022-09-22 13:25 UTC
If the websocket upgrade fails, zio-http (netty) returns with a 400 Bad Request response. This can be simulated by running the echo server example and passing a long bearer token to it (https://github.com/zio/zio-http/issues/1549)

When using 
```scala
ZHttpAdapter.makeHttpService(interpreter)
```

from `caliban-zio-http`, it does not return with the above demonstrated error, but instead it never returns with a response (eventually leading to a gateway timeout in our case).

**Comment by paulpdaniels** [comment] 2022-09-23 06:07
I'm not sure if this is a caliban error, it looks like it might be related to how tapir is handling it, since `makeHttpService` shouldn't be handling the websocket upgrade anyway, it should be `makeWebSocketService`, unless I'm misunderstanding the issue.

**Comment by vigoo** [comment] 2022-09-23 06:29
That's possible, I forgot tapir is involved :) Will check soon.

**Comment by vigoo** [comment] 2022-09-23 07:32
Investigated this a bit further and realized that tapir-zio-http does not even support websockets (as your documentation also states), and we are using the tapir-based `makeHttpService`. 

So I was wrong about the issue, what really happens is that in case the headers got trimmed (because they are too long) something either within tapir or caliban makes  the request never finish. Is there anything in caliban that some missing headers could affect like this?

**Comment by ghostdogpr** [comment] 2022-09-24 01:41
@vigoo I just did a few tests and:
- the problem only happens with zio-http, it works fine with the other adapters
- it doesn't even enter in caliban's code

So the issue is either with zio-http or with the tapir interpreter for it.

**Comment by ghostdogpr** [comment] 2022-09-24 01:45
I think it's zio-http? I made a route like this `case _ -> !! / "api" / "health" => Http.succeed(Response.ok)` and sent a too long header, it doesn't hang the first time but then it hangs on the next calls.

**Comment by ghostdogpr** [comment] 2022-10-28 08:37
Closing as I think it's a zio-http issue (see above)

**Closed as completed by ghostdogpr** 2022-10-28 08:37 UTC

**Comment by guizmaii** [comment] 2022-10-28 08:39
Where can we track the fix of this issue?

**Comment by ghostdogpr** [comment] 2022-10-28 08:43
I don't think there is one 😄  (traveling now so can't really do it easily)
