### ISSUE TITLE
Since 2.8.0 compilation take forever

### ISSUE THREAD

**Issue by strokyl** [ghostdogpr/caliban#2331] opened 2024-07-08 08:39 UTC
Unfortunately, the code I am working on is closed source. But since 2.8.0 (same issue 2.8.1) compilation take forever and never finish.

**Comment by kyri-petrou** [comment] 2024-07-08 08:44
Hi @strokyl, thanks for reporting. What version of Scala are you using?

EDIT: Also, can you please confirm whether the issue isn't happening with `v2.7.2`? There were some changes done to derivation in both `v2.7.2` and `v2.8.0` and just want to make sure I'm looking at the right place

**Comment by kyri-petrou** [comment] 2024-07-08 08:46
Also, are you using semi-auto or auto derivation of schemas in your project?

**Comment by ghostdogpr** [comment] 2024-07-08 08:46
Also: auto or semi-auto derivation?

If you compile with IntelliJ it is possible to see which compile unit is currently happening so it could give important hints (phase, file). More here: https://www.jetbrains.com/help/idea/compile-and-build-scala-projects.html#scala_build

**Comment by strokyl** [comment] 2024-07-08 12:33
Everything is working fine with `v3.4.2`. We have this issue when compiling with sbt (1.10.1) and we are using scala `3.4.2`.
Also we are using semi-auto derivation

**Comment by kyri-petrou** [comment] 2024-07-08 14:58
> Everything is working fine with v3.4.2

Do you mean with `v2.7.2`?

> we are using scala 3.4.2

I have a feeling on what might be going wrong; Can you try compiling either with Scala `3.3.3` or `3.5.0-RC3` and let me know if you're seeing an improvement? If that's not possible, can you disable any warn-unused compiler flags?

**Comment by kyri-petrou** [comment] 2024-07-08 17:03
I'm actually really not sure on what's going on. I can't really find anything that would explain this. Are you certain that there weren't any code changes or updates to any other dependencies (perhaps transitive, like ZIO?)

If you're certain that there aren't any other updates and there weren't any code changes, I don't really know what's going on. I have 2x Scala 3 services using Caliban at $WORK and didn't observe any regressions with compilation times. If you could provide some compiler profiling data I might be able to help but at this stage everything is just a shot in the dark 😕

**Comment by strokyl** [comment] 2024-07-10 09:01
> Do you mean with v2.7.2?

Yes sorry, I mean v2.7.2

> I have a feeling on what might be going wrong; Can you try compiling either with Scala 3.3.3 or 3.5.0-RC3 and let me know if you're seeing an improvement? If that's not possible, can you disable any warn-unused compiler flags?

Scala 3.5.0-RC3 neither 3.3.3 solve the issue 


I took a deeper look at our build.sbt file, the compile target on root calls an entry point in our code, and this is what takes forever. So it's not a compilation issue. When tracking down what takes forever, I found this line:
```
  val api = caliban.graphQL[R, Queries, Mutations, Subscriptions](resolver = ClustersResolver.resolver)
  ```

**Comment by kyri-petrou** [comment] 2024-07-10 10:12
@strokyl this sounds to me quite like 1 of 2 things:

1. The custom R schema isn't extending the correct trait. Are you extending `GenericSchema[R]` or `CommonSchemaDerivation[R]`? If you're not using `CommonSchemaDerivation`, please try with that and let me know if that improves things
2. There might be some auto-derivation in the codebase. Are you certain there aren't any usages of `Schema.auto` or `Schema.Auto` in the codebase?

**Comment by ghostdogpr** [comment] 2024-08-22 00:28
Closing this for now but let us know if you have more details (see questions above).

**Closed as completed by ghostdogpr** 2024-08-22 00:28 UTC
