### ISSUE TITLE
ValidationError on _Entity Union for subgraphs

### ISSUE THREAD

**Issue by coderfromhere** [ghostdogpr/caliban#1525] opened 2022-11-29 15:20 UTC
I'm getting the following error when using `caliban.federation`:

```
Exception in thread "zio-fiber-118" caliban.CalibanError$ValidationError: ValidationError Error: Union _Entity contains the following non Object types: .
```

The set is empty, yet the validation error is still thrown. It happens when one of `EntityResolver`s return a `List[A]`.

I guess it is related to this check https://github.com/ghostdogpr/caliban/issues/230

Is there really a spec restriction on federated subgraph query's return values so that they could never be list data?

The query structure looks something like that (the filters are different):
```
extend type Query {
    item(filter: ItemFilter!): Item!
    items(filter: ItemsFilter!): [Item!]!
}
```

**Comment by paulpdaniels** [comment] 2022-11-30 05:07
Can you share a bit more about how your entity resolvers are built? I'm unclear on what you mean by return a `List[A]` also which object are you trying to extend?

**Comment by avanov** [comment] 2022-11-30 20:43
@paulpdaniels here's a reproducible sample project: https://github.com/avanov/scala-caliban-sample

Run `make test`, see that the test suite passes for the regular api interpreter. Then try this to get the validation error: https://github.com/avanov/scala-caliban-sample/blob/74038ba8e52b31e752d30a6fa29f09fc22606d9d/src/main/scala/example/Resolver.scala#L110-L112

**Comment by paulpdaniels** [comment] 2022-12-01 02:22
@avanov yeah it's because that is not a valid entity resolver, the `_entities` resolver can only return one result per arg and they need to be in the shape of an entity.

https://www.apollographql.com/docs/federation/subgraph-spec#resolving-query_entities

**Comment by paulpdaniels** [comment] 2022-12-01 02:23
You only need the first entity resolver in the list not the second one

**Comment by avanov** [comment] 2022-12-01 02:58
@paulpdaniels it's not clear how I accommodate both `getItem` and `getItems` within a single `EntityResolver` that's supposed to be resolved differently depending on two different input argument types. [This example in the caliban repo](https://github.com/ghostdogpr/caliban/blob/series/2.x/examples/src/main/scala/example/federation/FederatedApi.scala#L64-L79) doesn't cover the case. What's the proper interpretation for the following line?
```
EntityResolver.from[CharacterArgs](args => ZQuery.fromZIO(CharacterService.findCharacter(args.name)))
```

Is it resolving from `CharacterArgs` to `Character`? in this case, what if I need to resolve from `Character2Args` to the same `Character`, or from `CharacterArgs` to `Character2`, or from `Character2Args` to `List[Character]`?

**Comment by avanov** [comment] 2022-12-01 03:07
@paulpdaniels it also isn't clear, in this case, why the following change helps to resolve the validation error without removing the second `EntityResolver` from the list: https://github.com/avanov/scala-caliban-sample/pull/1

**Comment by paulpdaniels** [comment] 2022-12-01 08:04
> getItem and getItems within a single EntityResolver

You can't, the gateway will send the keys that it is expecting results for in an array

```
[{"__typename": "Item", "key": 1}, {"__typename": "Item", "key": 2}]
```

It expects back a single item for each key or `null`. The `federation` wrapper handles unwrapping the array of args and calls the respective `EntityResolver` for each. If you want to have batched resolution then you can make sure that the `ZQuery` you return is using a `DataSource.Batched` under the hood.

> Is it resolving from CharacterArgs to Character? in this case, what if I need to resolve from Character2Args to the same Character, or from CharacterArgs to Character2, or from Character2Args to List[Character]?

You can see a more comprehensive example here: https://github.com/apollographql/apollo-federation-subgraph-compatibility/blob/main/implementations/caliban/src/main/scala/ProductApi.scala

> it also isn't clear, in this case, why the following change helps to resolve the validation error without removing the second EntityResolver from the list:

This works because you are now making it return an object type which can be correctly unioned. In the federation wrapper we union together all of the `Resolver` types to generate the `_Entity` type that the gateway expects.

**Comment by avanov** [comment] 2022-12-01 12:15
@paulpdaniels thanks, I think now I understand where my reasoning was wrong. I assumed that the federated API aspect had to have all counterparts to queries implemented in the main `RootResolver`, but now it looks like the federated aspect is only concerned about resolving entities via their `@GQLKey`s, and the queries `item(...) {...}` and `items(...) {...}` are still resolved directly via the `RootResolver(queries)` that's annotated with `@@ withFederation`. Is that correct?

**Comment by paulpdaniels** [comment] 2022-12-01 17:03
@avanov yes that is correct, the gateway will automatically union the fields the `Query` and `Mutation` types creating the corresponding supergraph versions of them. So the `EntityResolvers` are only needed to "stitch" together entities provided by different subgraphs

**Closed as completed** 2022-12-05 02:33 UTC
