### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by ghostdogpr** [ghostdogpr/caliban#1497] opened 2022-11-03 00:18 UTC
A few of them need some manual resolving

<img width="544" alt="Screen Shot 2022-11-03 at 9 18 06 AM" src="https://user-images.githubusercontent.com/7413894/199625898-f3fecb09-3279-4b12-8a05-fce529e1add1.png">

**Comment by kyri-petrou** [comment] 2022-11-08 22:01
Took a look at the ZIO one, and it seems to be related to the ScalaJS version and related to this issue: https://github.com/zio/zio/issues/7496

Since ScalaJS ZIO seems to be used in [tests only](https://github.com/ghostdogpr/caliban/blob/series/2.x/build.sbt#L354-L355), one workaround would be to temporarily use version 2.0.2 for the ScalaJS test libraries until the upstream issue is fixed. Thoughts? I can make a PR for it

**Comment by ghostdogpr** [comment] 2022-11-08 23:53
@kyri-petrou hmm let's wait for a fix, because it might transitively cause the error for our users which is not great

**Comment by kyri-petrou** [comment] 2022-11-09 06:46
@ghostdogpr it seems that the `async-http-client-backend-zio` package is no longer maintained so `AsyncHttpClientZioBackend` is marked as deprecated in `sttp` 3.8.3

There are 2 alternative ZIO backends available:

1. `HttpClientZioBackend`
2.`ArmeriaZioBackend`

Main issue with (1) is that it's built on-top of `java.net.http.HttpClient` which is only available in JDK11+. As for (2), the issue I see with that is bringing another dependency into the project. It seems that `async-http-client-backend-zio` is a Test dependency in most modules except `caliban-tools`

**Comment by ghostdogpr** [comment] 2022-11-09 06:52
@paulpdaniels @frekw any opinion regarding the above point?

**Comment by kyri-petrou** [comment] 2022-11-09 07:02
To add to the above, the client seems to be used only here (in non-test code) https://github.com/ghostdogpr/caliban/blob/f3b9210a895859b2a13a66a7bad33ec8cb06b3eb/tools/src/main/scala/caliban/tools/SchemaLoader.scala#L33.

Would it be better to deprecate the method and create a new one where the user needs to provide an `SttpClient` implementation instead? Then it would just leave us figuring out what to use in the test suites / examples.

**Comment by ghostdogpr** [comment] 2022-11-09 07:04
Yeah I think that would be nice! We can move the SttpClient dependency back to ZIO environment.

**Comment by paulpdaniels** [comment] 2022-11-10 08:03
Yeah I would suggest moving the `SttpBackend[Task, Any]` requirement into the environment and not have any strict requirements on the implementation

**Comment by kyri-petrou** [comment] 2022-11-10 10:12
Sounds good, I'll try and make a PR in the next couple of days.

Based on a brief look that I had earlier, it seems that the "trickiest" part is that the `SchemaLoader` is used by the `calibanGenSchema` CLI command, which means that even after moving the `SttpBackend` requirement into the environment, we'll either have to:
1. provide a client implementation, or
2. introduce a CLI argument and resolve it to an implementation (assuming the user also added the corresponding dependency)
3. Something I haven't thought of 😅

(2) seems to me a bit like asking too much from the user for something that is only used internally by the CLI tool, and (1) takes us back to the question of choosing a new default implementation now that  `AsyncHttpClientZioBackend` is deprecated.

**Comment by paulpdaniels** [comment] 2022-11-10 14:54
Didn't `sttp` drop support for java8? Can't we just use the `HttpClient` backend?

**Comment by kyri-petrou** [comment] 2022-11-13 04:42
> Can't we just use the HttpClient backend?

The issue is that the test suites run on both JDK8 and JDK11. If we're happy to remove the JDK8-based test suites and drop support for JDK8 then we can use the `HttpClient`.

**Comment by ghostdogpr** [comment] 2022-11-13 12:36
How do the tests work if they dropped jdk8 support? 😅

**Closed as completed** 2022-12-06 23:24 UTC
Labels: good first issue

**Comment by kyri-petrou** [comment] 2022-12-06 23:32
@ghostdogpr there's still STTP on that list but I think that's a bit more involved so many we can open a separate issue
